
# Use a base image with the required runtime environment
# Use a base image with JDK
FROM tambenikita391/openjdk-24-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY . /app

# Start the application
CMD ["java", "-jar","directory-service.jar"]
