# Use a base image with JDK
FROM tambenikita391/openjdk-24-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY hospiital-management-0.0.1-SNAPSHOT.jar /app/patient-service.jar

# Start the application
CMD ["java", "-jar","patient-service.jar"]
