# Base WORKDIR => /
FROM openjdk:24-jdk-slim

WORKDIR /app

# Copy the application JAR file
COPY target/patient-service-0.0.1-SNAPSHOT.jar /app/patient-service.jar

# Start the application
CMD ["java", "-jar","patient-service.jar"]
