
# Use a base image with the required runtime environment
# Use a base image with JDK
FROM tambenikita391/openjdk-24-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY ./target/appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

# Start the application
CMD ["java", "-jar", "/app/appointment-service.jar"]
