# Base WORKDIR => /
FROM tambenikita391/openjdk-24-jdk

WORKDIR /app

# Copy the application JAR file
COPY target/appointment-service-0.0.1-SNAPSHOT.jar /app/appointment-service.jar

# Start the application
CMD ["java", "-jar","appointment-service.jar"]



