
# Use a base image with the required runtime environment
# Use a base image with JDK
FROM openjdk:11-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application JAR file
COPY target/case-service-0.0.1-SNAPSHOT.jar /app/case-service.jar

# Start the application
CMD ["java", "-jar","case-service.jar"]