
# Base WORKDIR => /
FROM tambenikita391/openjdk-24-jdk

WORKDIR /app

# Copy the application JAR file
COPY target/case-service-0.0.1-SNAPSHOT.jar /app/case-service.jar

# Start the application
CMD ["java", "-jar","case-service.jar"]


