name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  build-and-push-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait Before Cleanup
        run: sleep 10

      - name: Remove Problematic Files
        run: |
          if [ -d "hospital-management/api-gateway/target" ]; then
            find hospital-management/api-gateway/target -name '*.html' -exec rm -f {} \;
          fi
        working-directory: hospital-management/api-gateway

      - name: Clean up Target Directory
        run: rm -rf hospital-management/api-gateway/target

      - name: Perform Google Formatter Check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/api-gateway

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: mvn org.codehaus.mojo:ossindex-maven-plugin:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build Code and Create Docker Images
        run: |
          mvn clean install -X
          mvn docker:build -Dimage.registry=${{secrets.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME
        working-directory: hospital-management/api-gateway

      - name: List Docker Images
        run: docker images

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push Docker Images
        run: |
          docker push ${{secrets.CONTAINER_REGISTRY_URL}}/api-gateway:$GITHUB_REF_NAME

  license-finder-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Pull License Finder Docker Image
        run: docker pull tambenikita391/license-finder:latest

      - name: Run License Finder Check
        run: |
          docker run --rm -v "$(pwd)/hospital-management/api-gateway:/scan" tambenikita391/license-finder:latest
        continue-on-error: true
