name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build code and create docker images
        working-directory: hospital-management/api-gateway
        run: mvn clean install docker:build -Dimage.registry=${{secrets.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push docker images
        run: |
         docker push ${{secrets.CONTAINER_REGISTRY_URL}}/api-gteway:$GITHUB_REF_NAME
