name: Build and Deploy API Gateway

on:
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Clone Repositories
        run: make clone

      - name: Print Git Status
        run: make git_status

      - name: Pull Latest Changes
        run: make git_pull

      - name: Stash Changes
        run: make git_stash

      - name: Build Library Project
        run: make build_lib

      - name: Build Services
        run: make build_services

      - name: Build Docker Images
        run: make build_images

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push Docker Images
        run: make push_images
