
name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build code and create docker images
        run:
          cd hospital-management/api-gateway && mvn clean install docker:build -Dimage.registry=*** -Dimage.tag=$GITHUB_REF_NAME

      - name: Push Docker Image for api-gateway
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/api-gateway:latest

      

