name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/api-gateway/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build code and create docker images
        run: |
          cd hospital-management/api-gateway
          mvn clean install docker:build -Dimage.registry=${{secrets.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}
            

      - name: Push Docker Image for api-gateway
        env:
          IMAGE_NAME: ${{secrets.DOCKER_REGISTRY_USER}}/api-gateway
          IMAGE_TAG: $GITHUB_REF_NAME
        run: |
          docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
