name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/appointment-service/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build code and create docker images
        run: |
          mvn clean install
          mvn docker:build -Dimage.registry=${{ secrets.CONTAINER_REGISTRY_URL }} -Dimage.tag=$GITHUB_REF_NAME
        working-directory: hospital-management/appointment-service

      - name: List Docker Images
        run: docker images

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push docker images
        run: |
          # Push the Docker image to the registry
          docker push ${{ secrets.CONTAINER_REGISTRY_URL }}/appointment-service:$GITHUB_REF_NAME
