name: Build and push base images

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USERNAMES: ${{ secrets.DOCKER_REGISTRY_USERNAMES }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Build license finder image
        run: |
          docker build -t ${DOCKER_REGISTRY_USERNAMES}/license-finder:latest -f license_finder .
        working-directory: dev-sec-ops/base-images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          docker-username: ${{ secrets.DOCKER_USERNAMES }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true

      - name: Push docker image
        run: docker push ${DOCKER_REGISTRY_USERNAMES}/license-finder:latest
