name: Build base images

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

env:
  DOCKER_REGISTRY_USER: tambenikita391

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Build license finder image
        run: |
          docker build -t ${DOCKER_REGISTRY_USER}/license-finder:latest -f license_finder .
        working-directory: dev-sec-ops/base-images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push docker image
        run: docker push ${DOCKER_REGISTRY_USER}/license-finder:latest
