name: Build and Push Docker Image

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USERNAMES: ${{ secrets.DOCKER_REGISTRY_USERNAMES }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t "${{ env.DOCKER_REGISTRY_USERNAMES }}/license-finder:latest" -f license_finder .
        working-directory: dev-sec-ops/base-images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMES }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push "${{ env.DOCKER_REGISTRY_USERNAMES }}/license-finder:latest"
