name: Base Image Build

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY_USERNAMES: ${{ secrets.DOCKER_REGISTRY_USERNAMES }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        run: |
          docker build -t "${DOCKER_REGISTRY_USERNAMES}/license-finder:latest" -f license_finder .
          docker push "${DOCKER_REGISTRY_USERNAMES}/license-finder:latest"
