name: Build, Push, and Logout

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_USERNAMES: ${{ secrets.DOCKER_REGISTRY_USERNAMES }}

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Build License Finder Image
        run: |
          docker build -t ${DOCKER_REGISTRY_USERNAMES}/license-finder:latest -f license_finder .
        working-directory: dev-sec-ops/base-images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAMES }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_REGISTRY_USERNAMES}/license-finder:latest

  logout:
    runs-on: ubuntu-latest
    steps:
      - name: Logout from Docker
        uses: docker/login-action@v2
        with:
          logout: true
