name: Build base images

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Build license finder image
        run: |
          cd ${GITHUB_WORKSPACE}/dev-sec-ops/base-images
          docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/license-finder:latest -f license_finder .

      - name: Login to docker registry
        uses: docker/login-action@v2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/license-finder:latest
