name: Build base images

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-base-images:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v3

      - name: Build image
        run: docker build -t ${{secrets.DOCKER_REGISTRY_USER}}/license-finder:latest -f base-images/license_finder .

      - name: Login to docker registry
        uses: docker/login-action@v2
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PAT }}
        

      
      - name: Push docker image
        run: docker push -t ${{secrets.DOCKER_REGISTRY_USER}}/license-finder:latest
   
