
name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3


      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER}}
          password: ${{ secrets.DOCKER_REGISTRY_PAT}}

      - name: Build Docker Image for directory-service
        run: 
          docker build -t ${{ secrets.DOCKER_REGISTRY_USER}}/directory-service:latest -f dockerfile .
        working-directory: hospital-management/directory-service

      - name: Push Docker Image for directory-service
        run: 
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/directory-service:latest

    

      

