
name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/hospital-management-console/**

jobs:
  build-and-push-hospital-management-console:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/api-gateway

      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: License finder
        run: |
          cd hospital-management/api-gateway
          docker pull tambenikita391/license-finder:latest
          docker run -v "$(pwd):/scan" tambenikita391/license-finder:latest
        continue-on-error: true
        
