
name: Build and Push openjdk-24-jdkDocker Image

on:
  push:
    paths:
      - dev-sec-ops/base-images/**

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_USER}}/openjdk-24-jdk:latest -f openjdk-24-jdk .
        working-directory: dev-sec-ops/base-images

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER}}
          password: ${{ secrets.DOCKER_REGISTRY_PAT}}

      - name: Push Docker Image
        run: |
          docker push ${{secrets.DOCKER_REGISTRY_USER}}/openjdk-24-jdk:latest

          
