
name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/patient-service/**

jobs:
  build-and-push-patient-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:format
        working-directory: hospital-management/patient-service

      - name: Perform google formatter check
        run: mvn com.spotify.fmt:fmt-maven-plugin:check
        working-directory: hospital-management/patient-service


      - name: GitLeaks Scan
        uses: zricethezav/gitleaks-action@v1.3.0

      - name: OSS Scan
        run: mvn ossindex:audit
        continue-on-error: true

      - name: OWASP Scan
        if: false
        run: mvn org.owasp:dependency-check-maven:check

      - name: Build code and create docker images
        run: |
          mvn clean install
          mvn docker:build -Dimage.registry=${{secrets.CONTAINER_REGISTRY_URL}} -Dimage.tag=$GITHUB_REF_NAME
        working-directory: hospital-management/patient-service
        
      - name: List Docker Images
        run: docker images

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_REGISTRY_USER}}
          password: ${{secrets.DOCKER_REGISTRY_PAT}}

      - name: Push docker images
        run: |
         docker push ${{secrets.CONTAINER_REGISTRY_URL}}/patient-service:$GITHUB_REF_NAME
         
         
         
